apiVersion: v1
kind: Pod
metadata:
  name: origin-web-console-smoke-test-pod
  labels:
    app: origin-web-console-smoke-test
spec:
  containers:
  - name: origin-web-console-smoke-test
    image: jhadvig/protractor-smoke-test:latest
    restartPolicy: Never
    imagePullPolicy: Always
    env:
    - name: CONSOLE_URL
      value: https://192.168.100.3:8443
