apiVersion: v1
kind: Pod
metadata:
  name: origin-web-console-smoke-test-pod
  labels:
    app: origin-web-console-smoke-test
spec:
  containers:
  - name: origin-web-console-smoke-test
    image: benjaminapetersen/origin-web-console-smoke-test
    imagePullPolicy: IfNotPresent
    env:
    - name: CONSOLE_URL
      value: https://10.192.213.145:8443
    - name: CONSOLE_USER
      value: bob
    - name: CONSOLE_PASSWORD
      value: bob
