apiVersion: v1
kind: Pod
metadata:
  name: origin-web-console-smoke-test-pod
  labels:
    app: origin-web-console-smoke-test
spec:
  containers:
  - name: origin-web-console-smoke-test
    image: benjaminapetersen/origin-web-console-smoke-test:v0.0.6
    env:
    - name: CONSOLE_PUBLIC_URL
      # NOTE: be sure to update this to be the correct IP address!
      value: https://10.13.129.111:8443
    - name: CONSOLE_USER_NAME
      value: bob
    - name: CONSOLE_PASSWORD
      value: bob
