apiVersion: apps/v1
kind: Deployment
metadata:
  name: origin-web-console-smoke-test-deployment
  labels:
    app: origin-web-console-smoke-test
spec:
  # replica set
  replicas: 1
  # selector = how the deployment finds pods to manage
  selector:
    matchLabels:
      app: origin-web-console-smoke-test
  template:
    metadata:
      labels:
        app: origin-web-console-smoke-test
    spec:
      restartPolicy: Always
      containers:
      - name: origin-web-console-smoke-test
        # see if we find it on dockerhub
        image: jhadvig/protractor-smoke-test:latest
        imagePullPolicy: Always
        # i think the env vars will work here...
        env:
        - name: CONSOLE_URL
          value: https://192.168.100.3:8443

